sudo: required
language: cpp
services:
- docker
before_install:
- docker pull ubuntu:16.04
script:
- docker build --tag SVMTool-ubuntu16 --build-arg BINTRAYKEY=$BINTRAYKEY --build-arg
  TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER -f ./Dockerfile-ubuntu16.04 .
after_success:
- docker run -t -d SVMTool-ubuntu16
- docker cp $(docker ps -n 1 -q):/src/SVMTool-1.3.1.tgz $HOME/SVMTool-1.3.1.tgz
before_deploy:
- git config --local user.name "Gael de Chalendar"
- git config --local user.email "kleag@free.fr"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: J2xFoKPUOgR2ok5mXMDewO8RhV3mhR+ViM/Wanu/tkEzrWdnLVv37+WvzOd1cmi2R8Ueot2dyntiZcQOTLkX8Nj1trydQGce8x5QqXzr5PG5QBfWinpKZd/hAkTMRL1z4Boo9ydVBJIY8u3zQu7/8pBacGRQ7UyTE+Q4sJmRt6etLqVtmBsTT89smcEAe/X66ptWhyzMcQ4PpUccSSicg9ti5h76vn5BvEwPgPQ8Qhe7vkNCPGsQmiqaBOpAk4i4fHrYG/yNjOKRNcD6/qu8p5sdSJfE3O1jiyXiwh4Tgdbg5mCa6jc3StmRXGTymKTXU76G317cY5kiFmJQxBXx8xRfX7wr3UBL1GI7jtrs91+5UyUwySHTd7m+txG1M9kOG0qP7TgbcjKPwI8VOfmXvb0eBuQ7mHi10ZSqUYwCWDzAIKF89qF42vOvJmXIsfWKTRBxVDOmHB8jtCfzFQYATnOSwWH7ZdrLqivGhzCzt/eP5IMWHBfocFyAH4V04YkjvXd9WsgbtCrjQeXY5K+S2VPhNJl3bWLrSJKSMxSnTI1OJXfhPNyhOSHJ0em1PJXVWBgx6o4dGzuHfFgWTL2O1s0s7qvDQj32mkeOsMnaCOIpLlLn4N/jJCvoHb/RHIFb9jJAbT9lMDgK4odQypRW3IGPFSmeMee4Aq8KlyOvf/k=
  file_glob: true
  file: $HOME/*.deb
  skip_cleanup: true
  on:
    repo: aymara/SVMTool
    tags: false
    all_branches: true
